### ISSUE TITLE
PATTERN name is not supported

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand-Language-Support#29]
The name of a PATTERN is red, it shouldn't be:

![image](https://user-images.githubusercontent.com/1159672/55968168-c5285b80-5c7b-11e9-9818-60b2222634a1.png)

**Comment by RieksJ** [comment]
The keywords `PATTERN`, `ENDPATTERN`, `PROCESS`, `ENDPROCESS`, `LATEX`, `MARKDOWN`, `SPEC` and `REST` are designated as deprecated. This  means they are coloured reddish - not the same colour as `invalid.illegal` texts, but sufficiently so to stimulate developers to no longer use them. This is also true for the ExecEngine function `NewStruct` (that is deprecated since we have the `_NEW` keyword in `VIOLATION`s).
